#!/usr/bin/python3PI
# -*- coding: utf-8 -*-
"""
Attributes:
    TEST_LIST_PIN_MODE: All pin-indexes must be set to the mode list
    pin_index: The index of the pin
    pin_mode: The mode of the pin (int)
    pin_mode_name: The mode-name of the pin
"""
TEST_LIST_PIN_MODE = [
    {
        "pin_index": 0,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 1,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1602,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 2,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 3,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 4,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 5,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 6,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 7,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 8,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 9,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 10,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 11,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 12,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 13,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 14,
        "pin_mode": 0x76,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PWM6_MODE_3",
    },
    {
        "pin_index": 15,
        "pin_mode": 0x7b,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PWM7_MODE_3",
    },
    {
        "pin_index": 16,
        "pin_mode": 0x0f,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "I2C1_MODE_2",
    },
    {
        "pin_index": 17,
        "pin_mode": 0x0f,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "I2C1_MODE_2",
    },
    {
        "pin_index": 18,
        "pin_mode": 0x60,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PWM1_MODE_6",
    },
    {
        "pin_index": 19,
        "pin_mode": 0x00,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "GPIO_MODE",
    },
    {
        "pin_index": 20,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 21,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 22,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 23,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 24,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 25,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 26,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 27,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 28,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 29,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 30,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 31,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 32,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 33,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 34,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    # {
    #     "pin_index": 35,
    #     "pin_mode": 0x7e,
    #     "pin_mdrv": 0x1e1601,
    #     "pin_mode_name": "SDIO_MODE_1",
    # },
    # {
    #     "pin_index": 36,
    #     "pin_mode": 0x7e,
    #     "pin_mdrv": 0x1e1601,
    #     "pin_mode_name": "SDIO_MODE_1",
    # },
    {
        "pin_index": 41,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 42,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 43,
        "pin_mode": 0x3c,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "I2S_TX_MODE_1",
    },
    {
        "pin_index": 44,
        "pin_mode": 0x3c,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "I2S_TX_MODE_1",
    },
    # {
    #     "pin_index": 0,
    #     "pin_mode": 0x10,
    #     "pin_mdrv": 0x1e1601,
    #     "pin_mode_name": "SDIO_MODE_1",
    # },
    # {
    #     "pin_index": 0,
    #     "pin_mode": 0x10,
    #     "pin_mdrv": 0x1e1601,
    #     "pin_mode_name": "SDIO_MODE_1",
    # },
    {
        "pin_index": 47,
        "pin_mode": 0x38,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "I2S_MCK_MODE_3",
    },
    {
        "pin_index": 48,
        "pin_mode": 0x39,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "I2S_RX_MODE_1",
    },
    {
        "pin_index": 49,
        "pin_mode": 0x3c,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "I2S_TX_MODE_1",
    },
    {
        "pin_index": 50,
        "pin_mode": 0x39,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "I2S_RX_MODE_1",
    },
    {
        "pin_index": 51,
        "pin_mode": 0x39,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "I2S_RX_MODE_1",
    },
    {
        "pin_index": 52,
        "pin_mode": 0xba,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PWM3_MODE_3",
    },
    {
        "pin_index": 53,
        "pin_mode": 0xb6,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PWM3_MODE_3",
    },
    {
        "pin_index": 54,
        "pin_mode": 0x9b,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_IR_IN_MODE_1",
    },
    {
        "pin_index": 55,
        "pin_mode": 0xf4,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE12_1",
    },
    {
        "pin_index": 56,
        "pin_mode": 0xf5,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE13_1",
    },
    {
        "pin_index": 57,
        "pin_mode": 0xf6,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE14_1",
    },
    {
        "pin_index": 58,
        "pin_mode": 0xf7,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE15_1",
    },
    {
        "pin_index": 59,
        "pin_mode": 0xf8,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE16_1",
    },
    {
        "pin_index": 60,
        "pin_mode": 0xa8,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_SDIO_RSTN_MODE_1",
    },
    {
        "pin_index": 61,
        "pin_mode": 0xe7,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_SR_PDN_MODE_2",
    },
    {
        "pin_index": 62,
        "pin_mode": 0xfb,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE19_1",
    },
    {
        "pin_index": 63,
        "pin_mode": 0xfc,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE20_1",
    },
    {
        "pin_index": 64,
        "pin_mode": 0xfd,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE21_1",
    },
    {
        "pin_index": 65,
        "pin_mode": 0xd7,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_I2CM0_MODE_1",
    },
    {
        "pin_index": 66,
        "pin_mode": 0xd7,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_I2CM0_MODE_1",
    },
    {
        "pin_index": 67,
        "pin_mode": 0xa7,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_SDIO_CDZ_MODE_4",
    },
    {
        "pin_index": 68,
        "pin_mode": 0x101,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE25_1",
    },
    {
        "pin_index": 69,
        "pin_mode": 0x00,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "GPIO_MODE",
    },
    {
        "pin_index": 70,
        "pin_mode": 0x00,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "GPIO_MODE",
    },
    {
        "pin_index": 71,
        "pin_mode": 0x104,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE28_1",
    },
    {
        "pin_index": 72,
        "pin_mode": 0x29,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "EMMC4B_MODE_2",
    },
    {
        "pin_index": 73,
        "pin_mode": 0x29,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "EMMC4B_MODE_2",
    },
    {
        "pin_index": 74,
        "pin_mode": 0x29,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "EMMC4B_MODE_2",
    },
    {
        "pin_index": 75,
        "pin_mode": 0x29,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "EMMC4B_MODE_2",
    },
    {
        "pin_index": 76,
        "pin_mode": 0x29,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "EMMC4B_MODE_2",
    },
    {
        "pin_index": 77,
        "pin_mode": 0x29,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "EMMC4B_MODE_2",
    },
    {
        "pin_index": 78,
        "pin_mode": 0x14,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "MSPI0_MODE_4",
    },
    {
        "pin_index": 79,
        "pin_mode": 0x14,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "MSPI0_MODE_4",
    },
    {
        "pin_index": 80,
        "pin_mode": 0x14,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "MSPI0_MODE_4",
    },
    {
        "pin_index": 81,
        "pin_mode": 0x14,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "MSPI0_MODE_4",
    },
    {
        "pin_index": 82,
        "pin_mode": 0x10f,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE39_1",
    },
    {
        "pin_index": 83,
        "pin_mode": 0x110,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE40_1",
    },
    {
        "pin_index": 84,
        "pin_mode": 0x111,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE41_1",
    },
    {
        "pin_index": 85,
        "pin_mode": 0x112,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE42_1",
    },
    {
        "pin_index": 86,
        "pin_mode": 0x113,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE43_1",
    },
    {
        "pin_index": 87,
        "pin_mode": 0x114,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE44_1",
    },
    {
        "pin_index": 88,
        "pin_mode": 0x115,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE45_1",
    },
    {
        "pin_index": 89,
        "pin_mode": 0x116,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE46_1",
    },
    {
        "pin_index": 90,
        "pin_mode": 0x117,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE47_1",
    },
    {
        "pin_index": 91,
        "pin_mode": 0x118,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE48_1",
    },
    {
        "pin_index": 92,
        "pin_mode": 0x119,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE49_1",
    },
    {
        "pin_index": 93,
        "pin_mode": 0x11a,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE50_1",
    },
    {
        "pin_index": 94,
        "pin_mode": 0x11b,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "PM_PAD_EXT_MODE51_1",
    },
    {
        "pin_index": 95,
        "pin_mode": 0x00,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "GPIO_MODE",
    },
    {
        "pin_index": 96,
        "pin_mode": 0x00,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "GPIO_MODE",
    },
    {
        "pin_index": 97,
        "pin_mode": 0x00,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "GPIO_MODE",
    },
    {
        "pin_index": 98,
        "pin_mode": 0x00,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "GPIO_MODE",
    },
    {
        "pin_index": 99,
        "pin_mode": 0x00,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "GPIO_MODE",
    },
    {
        "pin_index": 100,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 101,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 102,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 103,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 104,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 105,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 106,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 107,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 108,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 109,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 110,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    },
    {
        "pin_index": 111,
        "pin_mode": 0x7e,
        "pin_mdrv": 0x1e1601,
        "pin_mode_name": "OTP_TEST_1",
    }
]
"""
Attributes:
    TEST_WHITELIST_PIN_MOD: Whitelist for some special pins
    pin_index: The index of the pin
    pin_mode: The mode of the pin (int)
    pin_mode_name: The mode-name of the pin
    pin_used_reason: Special reasons for pin pin Settings
"""
TEST_WHITELIST_PIN_MOD = [
    {
        "pin_index": 45,
        "pin_name": "PAD_PM_UART_TX",
        "pin_mode": 0,
        "pin_mode_name": "Not Set",
        "pin_used_reason": "support for soc uart Control console",
    },
    {
        "pin_index": 46,
        "pin_name": "PAD_PM_UART_RX",
        "pin_mode": 0,
        "pin_mode_name": "Not Set",
        "pin_used_reason": "support for soc uart Control console",
    },
    {
        "pin_index": 61,
        "pin_name": "PAD_PM_GPIO5",
        "pin_mode": 0x00,
        "pin_mode_name": "GPIO_MODE",
        "pin_used_reason": "support for CPU Power IDAC regulate",
    },
    {
        "pin_index": 62,
        "pin_name": "PAD_PM_GPIO4",
        "pin_mode": 0x00,
        "pin_mode_name": "GPIO_MODE",
        "pin_used_reason": "support for DDR Power IDAC regulate",
    },
    {
        "pin_index": 43,
        "pin_name": "PAD_PM_GPIO12",
        "pin_mode": 0x00,
        "pin_mode_name": "GPIO_MODE",
        "pin_used_reason": "support for CPU Power VID regulate",
    },
    {
        "pin_index": 52,
        "pin_name": "PAD_PM_GPIO10",
        "pin_mode": 0x00,
        "pin_mode_name": "GPIO_MODE",
        "pin_used_reason": "support for DDR Power VID regulate",
    },

    {
        "pin_index": 20,
        "pin_name": "PAD_SD0_CDZ",
        "pin_mode": 0x00,
        "pin_mode_name": "SD0_CDZ_MODE_1",
        "pin_used_reason": "support for Kernel SD Card CDZ",
    },
    {
        "pin_index": 21,
        "pin_name": "PAD_SD0_D1",
        "pin_mode": 0x00,
        "pin_mode_name": "SD0_MODE_1",
        "pin_used_reason": "support for Kernel SD Card Data",
    },
    {
        "pin_index": 22,
        "pin_name": "PAD_SD0_D0",
        "pin_mode": 0x00,
        "pin_mode_name": "SD0_MODE_1",
        "pin_used_reason": "support for Kernel SD Card Data",
    },
    {
        "pin_index": 23,
        "pin_name": "PAD_SD0_CLK",
        "pin_mode": 0x00,
        "pin_mode_name": "SD0_MODE_1",
        "pin_used_reason": "support for Kernel SD Card CLK",
    },
    {
        "pin_index": 24,
        "pin_name": "PAD_SD0_CMD",
        "pin_mode": 0x00,
        "pin_mode_name": "SD0_MODE_1",
        "pin_used_reason": "support for Kernel SD Card CMD",
    },
    {
        "pin_index": 25,
        "pin_name": "PAD_SD0_D3",
        "pin_mode": 0x00,
        "pin_mode_name": "SD0_MODE_1",
        "pin_used_reason": "support for Kernel SD Card DATA",
    },
    {
        "pin_index": 26,
        "pin_name": "PAD_SD0_D2",
        "pin_mode": 0x00,
        "pin_mode_name": "SD0_MODE_1",
        "pin_used_reason": "support for Kernel SD Card DATA",
    },
    {
        "pin_index": 44,
        "pin_name": "PAD_PM_GPIO11",
        "pin_mode": 0x00,
        "pin_mode_name": "GPIO_MODE",
        "pin_used_reason": "support for Kernel SD Card power crtl",
    },
    {
        "pin_index": 27,
        "pin_name": "PAD_FUART_RTS",
        "pin_mode": 0x00,
        "pin_mode_name": "EJ_MODE_1",
        "pin_used_reason": "support for Jink Link Debug,Set in IPL by CONFIG_ENABLE_JTAG",
    },
    {
        "pin_index": 28,
        "pin_name": "PAD_FUART_CTS",
        "pin_mode": 0x00,
        "pin_mode_name": "EJ_MODE_1",
        "pin_used_reason": "support for Jink Link Debug,Set in IPL by CONFIG_ENABLE_JTAG",
    },
    {
        "pin_index": 29,
        "pin_name": "PAD_FUART_RX",
        "pin_mode": 0x00,
        "pin_mode_name": "EJ_MODE_1",
        "pin_used_reason": "support for Jink Link Debug,Set in IPL by CONFIG_ENABLE_JTAG",
    },
    {
        "pin_index": 30,
        "pin_name": "PAD_FUART_TX",
        "pin_mode": 0x00,
        "pin_mode_name": "EJ_MODE_1",
        "pin_used_reason": "support for Jink Link Debug,Set in IPL by CONFIG_ENABLE_JTAG",
    },
    {
        "pin_index": 47,
        "pin_name": "PAD_PM_PSPI0_INT",
        "pin_mode": 0x00,
        "pin_mode_name": "PM_SDIO_CDZ_MODE_2",
        "pin_used_reason": "support for Kernel SDIO CDZ",
    },
    {
        "pin_index": 48,
        "pin_name": "PAD_PM_PSPI0_DI",
        "pin_mode": 0x00,
        "pin_mode_name": "PM_SDIO_MODE_3",
        "pin_used_reason": "support for Kernel SDIO Card DATA",
    },
    {
        "pin_index": 49,
        "pin_name": "PAD_PM_PSPI0_DO",
        "pin_mode": 0x00,
        "pin_mode_name": "PM_SDIO_MODE_3",
        "pin_used_reason": "support for Kernel SDIO Card DATA",
    },
    {
        "pin_index": 50,
        "pin_name": "PAD_PM_PSPI0_CK",
        "pin_mode": 0x00,
        "pin_mode_name": "PM_SDIO_MODE_3",
        "pin_used_reason": "support for Kernel SDIO Card DATA",
    },
    {
        "pin_index": 51,
        "pin_name": "PAD_PM_PSPI0_CZ",
        "pin_mode": 0x00,
        "pin_mode_name": "PM_SDIO_MODE_3",
        "pin_used_reason": "support for Kernel SDIO Card DATA",
    },
    # pin 52被设置了两次
    # 1.DDR Power VID regulate
    # 2.support for Kernel SDIO DATA
    # {
    #     "pin_index": 52,
    #     "pin_name": "PAD_PM_GPIO10",
    #     "pin_mode": 0x00,
    #     "pin_mode_name": "PM_SDIO_MODE_3",
    #     "pin_used_reason": "support for Jink Link Debug",
    # }

]
"""
Attributes:
    TOOL_IO_CHECK: IO_CHECK Tool path
"""
TOOL_IO_CHECK = "/mnt/scripts_system/cases/platform/resource/board/prog_io_check"
